[package]
name = "string-music"
version = "1.0.0"
description = "String Music"
authors = ["Mutton_String"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "string_music_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11.0", features = ["protocol-asset", "macos-private-api", "devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-prevent-default = "5"
tauri-plugin-decorum = "1.1.1"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
tauri-plugin-process = "2"
tauri-plugin-backpressed = "0.1.0"
tauri-plugin-store = "2"
tauri-plugin-log = "2"
tauri-plugin-fs = { version = "2.0.0", features = ["watch"] }
mundy = { version = "0.2", features = ["accent-color"] }
wry = "0.55"
futures = "0.3"
log = "0.4"
chrono = "0.4"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
